### ISSUE TITLE
TypeError: Cannot read property 'replaceChild' of null at Function.replaceChildWithTree

### ISSUE THREAD

**Issue by AugustoAleGon** [alimek/react-native-tooltip-menu#1]
I am implementing a simple example with React-native-tooltip-menu but I am having the following error: 

TypeError: Cannot read property 'replaceChild' of null  at Function.replaceChildWithTree
```

View style={styles.viewContainer}>

          <ReactNativeTooltipMenu
            buttonComponent={
              <View
                style={{
                  backgroundColor: 'purple',
                  padding: 10,
                  borderRadius: 25
                }}
              >
                <Text style={{ color: 'white', flex: 1 }}>Click me to show tooltip!</Text>
              </View>
            }
            items={[
              {
                label: 'Label #1',
                onPress: () => console.log('Hello label 1!')
              },
              {
                label: 'Label #2',
                onPress: () => console.log('Hello label 2')
              },
            ]}
          />
        </View>
```

This is my code nothing really different from the example. I hope you can help me with that issue.
Thanks.

**Comment by alimek** [comment]
Hi @AugustoAleGon ,

Could you give more details of your RN version and how you load `ReactNativeTooltipMenu` ?
Do you have problems with Example project, because I have just upgraded Example to latest version of ReactNative and it works normally.

**Comment by alimek** [comment]
close till you will not provide any extra details
