### ISSUE TITLE
Is there any method to change the direction of the menu component?

### ISSUE THREAD

**Issue by opp100** [alimek/react-native-tooltip-menu#3]
Dear author,

Thanks of the amazing plugin. Everything goes excellent, but is there any way to change the direction such as from top drop down, or pop from left hand side to right hand side?

Kind regards

**Comment by alimek** [comment]
Hi @opp100, I would like to extend this in future, but currently i am out of time to do this, but PR are welcome :)

**Comment by diegogonzalez2105** [comment]
buenas quiero poner estilos en casa label
