### ISSUE TITLE
Triangle

### ISSUE THREAD

**Issue by lisowska** [alimek/react-native-tooltip-menu#4]
hi,
It is possible to change the position and color of triangle. I want to add marginLeft and add new color, but now it is not possible.

**Comment by alimek** [comment]
Hi @lisowska , just checked code and your're right. There is no prop to overwrite triangle styles.

You can extend this if you want, PR are welcome :) if not, I can put this on my list, but currently no time to implement that.

**Comment by lisowska** [comment]
Hi @alimek I will try doing PR :)

**Comment by poolsideCoder** [comment]
Did you find any solution for the triangle problem @alimek

**Comment by alimek** [comment]
@poolsideCoder sorry but i dont have time to add this option now, but feel free to create PR for it
