### ISSUE TITLE
PropTypes is deprecated in React 15.5

### ISSUE THREAD

**Issue by FedeG** [alimek/react-native-tooltip-menu#6]
I'm develop this issue for update you package to react16, in this repository: https://github.com/Devecoop/react-native-tooltip-menu

**Comment by alimek** [comment]
feel free to create pull request

**Comment by FedeG** [comment]
This issue are fixed in https://github.com/alimek/react-native-tooltip-menu/pull/7

**Comment by alimek** [comment]
thanks, merged
